name: Check health

on:
  schedule:
    - cron : '0 11 * * *'

jobs:
  check_heath_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Wget health
        run: |
          wget https://fso-ci-poke.herokuapp.com/health
